export const tweaks = $state({
  obsRadius: 11,
  obsWeight: 3,
  obsGlowBlur: 8,
  obsGlowOpacity: 0.7,
  lineWeight: 4,
  lineGlowBlur: 8,
  lineGlowOpacity: 0.5,
  polyWeight: 3,
  polyFillOpacity: 0.25,
  polyGlowBlur: 10,
  polyGlowOpacity: 0.5,
  combiWeight: 3,
  combiFillOpacity: 0.15,
  combiGlowBlur: 10,
  combiGlowOpacity: 0.5,
  landmarkScale: 1.06,
  landmarkShadowBlur: 12,
  landmarkYLift: 8
});
